#include <conio.h>
#include <dos.h>
#include "C:\Windows\Desktop\screens\_eureka1.h"
#include "C:\Windows\Desktop\screens\_eureka2.h"
#include "C:\Windows\Desktop\screens\_123boot.h"
#include "C:\Windows\Desktop\screens\_123empt.h"
#include "C:\Windows\Desktop\screens\_123.h"
#include "C:\Windows\Desktop\screens\_word.h"
#include "C:\Windows\Desktop\screens\_pmaster.h"
#include "C:\Windows\Desktop\screens\_pmastr2.h"
#include "C:\Windows\Desktop\screens\_norton1.h"
#include "C:\Windows\Desktop\screens\_norton2.h"
#include "C:\Windows\Desktop\screens\_norton3.h"
#include "C:\Windows\Desktop\screens\_norton4.h"

void main()
{
	puttext(1,1,80,25,screen_H);
	sleep(10);
	puttext(1,1,80,25,eureka2);
	sleep(10);
	puttext(1,1,80,25,screen_123boot);
	sleep(10);
	puttext(1,1,80,25,screen_123empt);
	sleep(10);
	puttext(1,1,80,25,screen_123);
	sleep(10);
	puttext(1,1,80,25,screen_word);
	sleep(10);
	puttext(1,1,80,25,screen_pmaster);
	sleep(10);
	puttext(1,1,80,25,screen_pmastr2);
	sleep(10);
	puttext(1,1,80,25,screen_norton1);
	sleep(10);
	puttext(1,1,80,25,screen_norton2);
	sleep(10);
	puttext(1,1,80,25,screen_norton3);
	sleep(10);
	puttext(1,1,80,25,screen_norton4);
	sleep(10);
	//getch();
	main();
}